export const routes = {
  HOMEPAGE_URL: "/",
  USER_REGISTRATION_URL: "/indRegistration",
  ORGANIZATION_REGISTRATION_URL: "/orgRegistration",
  REGISTRATION_TYPES_URL: "/registration",
  USER_LOGIN_URL: "/login",
  USER_LOGOUT_URL: "/logout",
  HELP_REQUESTS_URL: "/help-requests",
  MY_ADVERTS_URL: "/my-adverts",
  MY_REQUESTS_URL: "/my-requests",
  MY_REQUESTS_URL_2: "/my-requests2",
  INFO_REQUEST_URL: "/info-request",
  VOLUNTEER_CHANCES_URL: "/opportunities",
  VOLUNTEER_ADVERTS_URL: "/volunteer-adverts",
  REQUESTS_URL: "/requests",
  DEALS_URL: "/deals",
  PROFILE_URL: "/profile",
  RECENSIONS_URL: "/recensions",
  NOTES_URL: "/notes",
  ADMIN_REQUESTS: "/admin-requests",
  ADMIN_ADVERTS: "/admin-adverts",
  ADMIN_USERS: "/admin-users",
};
